### ISSUE TITLE
references for insect prices

### ISSUE THREAD

**Issue by wgwz** [TinyFarms/OpenBugFarm#4]
[From the insect prices portion of the wiki:](https://github.com/TinyFarms/OpenBugFarm/wiki/Cricket-prices)
There are no references to the where the data came from. It's not that I don't believe the data, but it's a year old. 
It would be cool to update this dynamically. 
Suggestions?

**Comment by valioDOTch** [comment]
I could try to script a small JS script which would fetch links in a list and parse them for prices with some regular expressions; then that could be published at tinyfarms.github.io like that
https://pages.github.com

**Comment by wgwz** [comment]
That would work. Just need a good reference for insect prices.
